# -*- coding: utf-8 -*-
"""Sample Code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-VzD5tT7FSDojkRofg34Zc7U6Sipqwhf
"""

class BankAccount(object):
  balance = 0
  def __init__(self,name):
    self.name = name
  
  def __repr__(self): 
    return "%s's account. Balance: $%.2f" % (self.name, self.balance)
  
  def show_balance(self):
    print "$%.2f" % (self.balance) 
    
  def deposit(self, amount): 
    if amount <= 0:
      print "Error, you can't deposit negative money"
    else:  
      print "You are depositing $%.2f" % (amount) 
      self.balance += amount
      # self.show_balance() 
  
  def withdraw(self, amount):
    if amount > self.balance:
      print "Error, insufficient funds"
    else:
      print "You are withdrawing $%.2f" % (amount) 
      self.balance -= amount
      # self.show_balance() 

my_account = BankAccount("Madison")
print my_account
my_account.deposit(2000)
my_account.withdraw(1000)
print my_account